export const APPOINTMENT_STATUS = Object.freeze({
  SCHEDULED: "SCHEDULED",
  CONFIRMED: "CONFIRMED",
  IN_ATTENDANCE: "IN_ATTENDANCE",
  FINISHED: "FINISHED",
  CANCELED: "CANCELED",
  NO_SHOW: "NO_SHOW",
});
