export const NOTIFICATION_TYPES = {
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_UPDATED: "APPOINTMENT_UPDATED",
  APPOINTMENT_CANCELED: "APPOINTMENT_CANCELED",
  APPOINTMENT_REMINDER: "APPOINTMENT_REMINDER",
  ATTENDANCE_STARTED: "ATTENDANCE_STARTED",
  ATTENDANCE_FINISHED: "ATTENDANCE_FINISHED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_PAID: "PAYMENT_PAID",
  GENERAL: "GENERAL",
};
